version: 2
updates:
- package-ecosystem: docker
  directory: "/v0.17.1"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/v0.18.1"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/v0.19.0"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/v0.21.3"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/v0.22.4"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/v0.24.6"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
