version: 1
update_configs:
  - package_manager: docker
    directory: /v0.17.1/Dockerfile
    update_schedule: daily
  - package_manager: docker
    directory: /v0.18.1/Dockerfile
    update_schedule: daily
  - package_manager: docker
    directory: /v0.19.0/Dockerfile
    update_schedule: daily
  - package_manager: docker
    directory: /v0.21.3/Dockerfile
    update_schedule: daily
  - package_manager: docker
    directory: /v0.22.4/Dockerfile
    update_schedule: daily
  - package_manager: docker
    directory: /v0.24.6/Dockerfile
    update_schedule: daily
