version: 1
update_configs:
  - package_manager: docker
    directory: /v0.17.1
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
  - package_manager: docker
    directory: /v0.18.1
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
  - package_manager: docker
    directory: /v0.19.0
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
  - package_manager: docker
    directory: /v0.21.3
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
  - package_manager: docker
    directory: /v0.22.4
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
  - package_manager: docker
    directory: /v0.24.6
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
